language: android

jdk: oraclejdk8

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator10.2
  - IOS_PROJECT="ios/HoloNet.xcodeproj"
  - IOS_SCHEME="HoloNet"

notifications:
  email: false
  slack:
    secure: OG2heblMGg8o00TLzkMaoTxuXrBQNMbuPtQeP1tIJ4psn1HdKrcbE7nwz1pP/N0cHN80HPmtqpJDP9lLh0kmnkAlrh2GGK1d9lbhmNNoCtClcrh6UVJTVUafrTlXkagNTbo4ZSve8T6itMMZWI/Cci/XbUclpv7CRoD4+M9lTwRO7keweCwoLvIRVagvZVs4ZdQkxe37Ed8le86///s3Y48/fPvmFsVJzBzHk9HotjOeF1UJvuKghHUzLQvIGcMSAcHqyTnAxvcYfByTiyhDzv84RfHzH682G+SVIsw+Oc7QPaqap0xGGdcTvlAFHQ9lyXl0zDVOsLd/Rq9jesrp1SNtEl7Wyx0UoZC0piw9kGlysqCDfwdBbHyRrsW1cj0xbzBTng+O5ECzwCjWulIi/cn+ebuWRgmaH3evDo8zeNIAz3w1V4LNaeDpj0ecljJj16NqoXzFy82Vc2nG6I9Atupu+QIOUYTRGPHiOlaVIA1Ts4rBx97P4GExeS84PRNUEBviGRzmKIJOngTx8Dt4/JkGlAEVSkByOWL+X6QSrsHTy/X9mkQONdE3tfCClF2wLapacesgNFb9OUHNhJTZOxxb5mV6A7s9obVOeX66gf6vy8q/VKJktpzv7+BjMyyJDvxXO8o/xTLIcwemv71FrH0ZUV9nefpETT5+Scg7hpk=

matrix:
  include:
    - language: objective-c
      osx_image: xcode8.2

      cache:
        directories:
        - ios/Carthage

      before_install:
        - "./ios/scripts/bootstrap-if-needed.sh"

      script:
        - xcodebuild -version
        - xcodebuild -showsdks
        - set -o pipefail && xcodebuild clean build test -project "$IOS_PROJECT" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "OS=10.1,name=iPhone 7 Plus" -configuration Release | xcpretty;
        - set -o pipefail && xcodebuild clean build test -project "$IOS_PROJECT" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "OS=9.3,name=iPhone 5" -configuration Release | xcpretty;

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
  licenses:
    - android-sdk-license-.+
    - '.+'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - cd android
  - ./gradlew clean build
